  
name: Deploy Hugo site to vps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: hugo --minify
        
       
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildtifact
          path: public

  rsync-to-vps:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: buildtifact
    
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0

        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --rsync-path="sudo rsync"'
          options: ''
          ssh_options: '-p ${{secrets.CONNECTION_PORT}}'
          src: '/'
          dest: '${{secrets.CONNECTION_LOC}}:/var/www/html'

      - name: Display status from deploy
        run:
           echo "${{ steps.deploy.outputs.status }}"
         
